# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'SpotCheck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
  pod 'RealmSwift', '~> 2.8.0'
  pod 'NumberMorphView'
  pod 'Alamofire', '~> 4.4.0'
  pod 'TextFieldEffects', '~> 1.3.2'
  

 #Pods for SpotCheck

end
